# Generated by Django 5.2.1 on 2025-05-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='Unknown', unique=True),
            preserve_default=False,
        ),
    ]
